spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/clients
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8442 # Utilisez un autre port si vous avez les deux applications sur la même machine
  ssl:
    key-store: classpath:BmwBackKeystore.jks # Chemin vers le keystore
    key-store-password: PAPA31032014 # Mot de passe du keystore
    key-store-type: JKS  # Type de keystore
    key-alias: BmwBack # Alias du keystore
    trust-store: classpath:esimTrustStore.jks
    trust-store-password: PAPA31032014


