spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/clients
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8441 # Utilisez un autre port si vous avez les deux applications sur la même machine



