spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/clients
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  profiles:
    default: dev
server:
  port: 8441



